---
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - apt-get -y update
  pre_build:
    commands:
      - aws sts get-caller-identity
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 20 sh -c "until docker info; do echo .; sleep 1; done"
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME --role-arn $AWS_ROLE_ARN
      - | 
        curl --progress-bar -L --header "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2hyaXMubGFpQGtvc2l0ZWNoLmNvbS5oayIsInJvbGUiOiJhZG1pbiIsImdyb3VwcyI6bnVsbCwicm9sZVBlcm1zIjpbWzI1NSwyNTUsMjU1LDI1NSwyNTUsMTI3LDFdLFsyNTUsMjU1LDI1NSwyNTUsMjU1LDEyNywxXV0sInNlc3Npb25UaW1lb3V0U2VjIjo1NDIsInNhYXNUb2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lKamFISnBjeTVzWVdsQWEyOXphWFJsWTJndVkyOXRMbWhySWl3aWMyVnlkbWxqWlZWellXZGxUMjVzZVNJNmRISjFaU3dpWm1seWMzUk1iMmRwYmlJNlptRnNjMlVzSW5CeWFYTnRZVWxrSWpvaU1UQXhOREF3TkRnMk56TTNPRFF3TkRNMU1pSXNJbWx3UVdSa2NtVnpjeUk2SWpNMExqZzNMakV6Tnk0eE5ERWlMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwyRndhUzV6Wnk1d2NtbHpiV0ZqYkc5MVpDNXBieUlzSW5KbGMzUnlhV04wSWpvd0xDSjFjMlZ5VW05c1pWUjVjR1ZFWlhSaGFXeHpJanA3SW1oaGMwOXViSGxTWldGa1FXTmpaWE56SWpwbVlXeHpaWDBzSW5WelpYSlNiMnhsVkhsd1pVNWhiV1VpT2lKVGVYTjBaVzBnUVdSdGFXNGlMQ0pwYzFOVFQxTmxjM05wYjI0aU9tWmhiSE5sTENKc1lYTjBURzluYVc1VWFXMWxJam94TmpZMU5qY3dPVEUzTURReExDSmhkV1FpT2lKb2RIUndjem92TDJGd2FTNXpaeTV3Y21semJXRmpiRzkxWkM1cGJ5SXNJblZ6WlhKU2IyeGxWSGx3WlVsa0lqb3hMQ0p6Wld4bFkzUmxaRU4xYzNSdmJXVnlUbUZ0WlNJNklrbHVaM0poYlNCTmFXTnlieUFvUTJocGJtRXBJRXhwYldsMFpXUWdLRWhMS1NBdElEVXpOalkwTmpJNE5EVTRNalF3T0RFMU5qZ2lMQ0p6WlhOemFXOXVWR2x0Wlc5MWRDSTZNekFzSW5WelpYSlNiMnhsU1dRaU9pSTROR0k0TXpBd01DMDJNV1V4TFRRNE1HWXRZVEJpTUMxak5XSmlOVGRsWW1VNU9URWlMQ0pvWVhORVpXWmxibVJsY2xCbGNtMXBjM05wYjI1eklqcDBjblZsTENKbGVIQWlPakUyTmpVMk56azBOVElzSW1saGRDSTZNVFkyTlRZM09EZzFNaXdpZFhObGNtNWhiV1VpT2lKamFISnBjeTVzWVdsQWEyOXphWFJsWTJndVkyOXRMbWhySWl3aWRYTmxjbEp2YkdWT1lXMWxJam9pVTNsemRHVnRJRUZrYldsdUluMC5QNWl3UzhMY242LWw4UlMtbU5aYm5KbUpTSmxoOVI0MVhCMFhUMmtmVTY0IiwiZXhwIjoxNjY1NjgyNTEwLCJpc3MiOiJ0d2lzdGxvY2sifQ.3Dy5TV3hl6r8qZ8tnu3KJvIOvCz_CuQz2hpaaUAsmY8" https://asia-southeast1.cloud.twistlock.com/aws-singapore-961145920/api/v1/util/twistcli > twistcli; chmod a+x twistcli;
      - ./twistcli version
 
  build:
    commands:
      - docker build --tag $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$TAG
      - kubectl apply -f deployment.yaml
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$TAG