apiVersion: v1
kind: Pod
metadata:
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  containers:
  - image: 109331241453.dkr.ecr.ap-east-1.amazonaws.com/nodejs-demo:latest
    name: nodejs-demo
    ports:
    - containerPort: 3000
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo
spec:
  selector:
    app: nodejs-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
