apiVersion: v1
kind: Pod
metadata:
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  containers:
  - image: nginx:1.14.2
    name: nginxapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nginxapp
spec:
  selector:
    app: nginxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
